routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Route::get('/{any}', 'SpaController@index')->where('any', '.*');
Route::get('/works', 'SpaController@index')->where('any', '.*')->name('home');

//
//Route::get('/','Frontend\HomeController@index')->name('home');
//Route::get('/blog','Frontend\BlogController@index')->name('blog.index');
//Route::get('/blog/{slug}','Frontend\BlogController@show')->name('blog.show');
//Route::get('/works','Frontend\WorksController@index')->name('work.index');
//Route::get('/works/{slug}','Frontend\WorksController@show')->name('work.show');
//Route::get('/works/like/{id}', 'Frontend\WorksController@like');
//Route::get('/service','Frontend\ServicesController@index')->name('service.index');
//Route::get('/service/{slug}','Frontend\ServicesController@show')->name('service.show');
//Route::get('/about','Frontend\AboutController@index')->name('about');
//
//Route::get('/tag/{slug}','Frontend\BlogController@tag')->name('tag.show');
//Route::get('/category/{slug}','Frontend\BlogController@category')->name('category.show');
//Route::post('/subscribe', 'Frontend\SubsController@subscribe');
//Route::post('/order', 'Frontend\MailController@order');
//Route::get('/verify/{token}', 'Frontend\SubsController@verify');
//Route::get('searchSimple', 'SearchController@index')->name('searchSimple');


Route::group(['prefix'=>'backend', 'namespace'=>'Backend','middleware'	=>	'admin'],function(){
    Route::get('/','DashboardController@index')->name('backend');
    Route::resource('/categories','CategoriesController');
    Route::resource('/tags','TagsController');
    Route::resource('/posts','PostsController');
    Route::resource('/services','ServicesController');
    Route::resource('/works_up','WorksController');
    Route::resource('/filters','FiltersController');
    Route::resource('/users','UsersController');
    Route::get('/comments', 'CommentsController@index')->name('comments');
    Route::get('/comments/toggle/{id}', 'CommentsController@toggle');
    Route::delete('/comments/{id}/destroy', 'CommentsController@destroy')->name('comments.destroy');
    Route::resource('/subscribers', 'SubsController');
    Route::resource('/sliders','SliderController');
    Route::resource('/menus','MenusController');
    Route::resource('/abouts','AboutController');
    Route::resource('/absliders','AbsSliderController');
    Route::resource('/commands','CommandsController');
    Route::resource('/frames','FrameController');
    Route::resource('/settings','SettingsController');
});

Route::group(['middleware' => 'guest'], function (){
    Route::get('/register' , 'Auth\AuthController@registerForm');
    Route::post('/register' , 'Auth\AuthController@register');
    Route::get('/login' , 'Auth\AuthController@loginForm')->name('login');
    Route::post('/login', 'Auth\AuthController@login');
});
Route::group(['middleware' => 'auth'], function (){
    Route::get('/logout' , 'Auth\AuthController@logout')->name('logout');
    Route::get('/profile', 'Auth\ProfileController@index');
    Route::post('/profile', 'Auth\ProfileController@store');
    Route::post('/comment' , 'Frontend\CommentsController@store');
});

app/Http/Controllers/Backend/AboutController.php
<?php

namespace App\Http\Controllers\Backend;

use App\About;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AboutController extends Controller
{
    public function index() {
        $abouts = About::all();
        return view('backend.abouts.index',[
            'abouts' => $abouts
        ]);
    }
    public function create() {
        return view('backend.abouts.create');
    }
    public function store(Request $request){
        $this->validate($request,[
            'title' => 'required',
            'content' => 'required',
            'image' => 'nullable|image'
        ]);
        About::create($request->all());
        return redirect()->route('abouts.index')->with('message','Страница успешно добавлена');
    }
    public function edit($id) {
        $about = About::find($id);
        return view('backend.abouts.edit',[
            'about' => $about
        ]);
    }
    public function update(Request $request, $id){
        $this->validate($request,[
            'title' => 'required',
            'content' => 'required',
            'image' => 'nullable|image'
        ]);
        $about = About::find($id);
        $about->update($request->all());
        return redirect()->route('abouts.index')->with('message','Страница успешно обновлена');
    }
    public function destroy($id){
        About::find($id)->delete();
        return redirect()->route('abouts.index')->with('message','Страница успешно удалена');
    }
}

app/Http/Controllers/Backend/AbsSliderController.php
<?php

namespace App\Http\Controllers\Backend;

use App\AboutSlider;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AbsSliderController extends Controller
{
    public function index() {
        $absliders = AboutSlider::all();
        return view('backend.absliders.index',[
            'absliders' => $absliders
        ]);
    }
    public function create(){
        return view('backend.absliders.create');
    }
    public function store(Request $request){
        $this->validate($request,[
            'title' => 'required',
            'content' => 'required',
            'image' => 'nullable|image'
        ]);
        $abslider = AboutSlider::add($request->all());
        $abslider->uploadImage($request->file('image'));
        return redirect()->route('absliders.index')->with('message','Слайдер успешно добавлена');
    }
    public function edit($id){
        $abslider = AboutSlider::find($id);
        return view('backend.absliders.edit',[
            'abslider' => $abslider
        ]);
    }
    public function update(Request $request, $id) {
        $this->validate($request,[
            'title' => 'required',
            'content' => 'required',
            'image' => 'nullable|image'
        ]);
        $abslider = AboutSlider::find($id);
        $abslider->update($request->all());
        $abslider->uploadImage($request->file('image'));
        return redirect()->route('absliders.index')->with('message','Слайдер успешно обновлен');
    }

    public function destroy($id){
        AboutSlider::find($id)->remove();
        return redirect()->route('absliders.index')->with('message','Слайдер успешно удален');
    }
}

app/Http/Controllers/Backend/CategoriesController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

class CategoriesController extends Controller
{
    public function index(){

        $categories = DB::table('categories')->orderBy('created_at','desc')->paginate(7);
        return view('backend.categories.index',
            ['categories' => $categories]
        );
    }
    public function create() {
        return view('backend.categories.create');
    }
    public function store(Request $request) {
        $this->validate($request, [
           'title' => 'required'
        ]);
        Category::create($request->all());
        return redirect()->route('categories.index')->with('message','Категория успешно добавлена');
    }
    public function edit($id){
        $category = Category::find($id);
        return view('backend.categories.edit',[
            'category'=>$category
        ]);
    }
    public function update(Request $request, $id){
        $this->validate($request,[
            'title' => 'required'
        ]);
        $category = Category::find($id);
        $category->update($request->all());
        return redirect()->route('categories.index')->with('message','Категория успешно обновлена');
    }
    public function destroy($id){
        Category::find($id)->delete();
        return redirect()->route('categories.index')->with('message','Категория успешно удалена');
    }
}

app/Http/Controllers/Backend/CommandsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Commands;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CommandsController extends Controller
{
    public function index() {
        $commands = Commands::all();
        return view('backend.commands.index',[
            'commands' => $commands
        ]);
    }
    public function create(){
        return view('backend.commands.create');
    }
    public function store(Request $request){
        $this->validate($request,[
            'title' => 'required',
            'image' => 'nullable|image'
        ]);
        $command = Commands::add($request->all());
        $command->uploadImage($request->file('image'));
        return redirect()->route('commands.index')->with('message','Сотрудник успешно добавлен');
    }
    public function edit($id){
        $command = Commands::find($id);
        return view('backend.commands.edit',[
            'command' => $command
        ]);
    }
    public function update(Request $request, $id) {
        $this->validate($request,[
            'title' => 'required',
            'image' => 'nullable|image'
        ]);
        $command = Commands::find($id);
        $command->update($request->all());
        $command->uploadImage($request->file('image'));
        return redirect()->route('commands.index')->with('message','Сотрудник успешно обновлен');
    }

    public function destroy($id){
        Commands::find($id)->remove();
        return redirect()->route('commands.index')->with('message','Сотрудник успешно удален');
    }
}

app/Http/Controllers/Backend/CommentsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Comment;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CommentsController extends Controller
{
    public function index() {
        $comments = Comment::all();
        return view('backend.comments.index',['comments'=>$comments]);
    }

    public function toggle($id) {
        $comment = Comment::find($id);
        $comment->toggleStatus();
        return redirect()->back();
    }

    public function destroy($id) {
        Comment::find($id)->remove();
        return redirect()->back();
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Alexusmai\YandexMetrika\YandexMetrika;
use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index(){
        return view('backend.home.index');
    }

}

app/Http/Controllers/Backend/FiltersController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Filter;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

class FiltersController extends Controller
{
    public function index(){

        $filters = DB::table('filters')->orderBy('created_at','desc')->paginate(7);
        return view('backend.filters.index',
            ['filters' => $filters]
        );
    }
    public function create() {
        return view('backend.filters.create');
    }
    public function store(Request $request) {
        $this->validate($request, [
            'title' => 'required'
        ]);
        Filter::create($request->all());
        return redirect()->route('filters.index')->with('message','Фильтер успешно добавлен');
    }
    public function edit($id){
        $filter = Filter::find($id);
        return view('backend.filters.edit',[
            'filter'=>$filter
        ]);
    }
    public function update(Request $request, $id){
        $this->validate($request,[
            'title' => 'required'
        ]);
        $filter = Filter::find($id);
        $filter->update($request->all());
        return redirect()->route('filters.index')->with('message','Фильтер успешно обновлен');
    }
    public function destroy($id){
        Filter::find($id)->delete();
        return redirect()->route('filters.index')->with('message','Фильтер успешно удален');
    }
}

app/Http/Controllers/Backend/FrameController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Framework;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class FrameController extends Controller
{
    public function index() {
        $frames = Framework::all();
        return view('backend.frames.index',[
            'frames' => $frames
        ]);
    }
    public function create(){
        return view('backend.frames.create');
    }
    public function store(Request $request){
        $this->validate($request,[
            'title' => 'required',
            'image' => 'nullable|image'
        ]);
        $frame = Framework::add($request->all());
        $frame->uploadImage($request->file('image'));
        return redirect()->route('frames.index')->with('message','Инструмент успешно добавлен');
    }
    public function edit($id){
        $frame = Framework::find($id);
        return view('backend.frames.edit',[
            'frame' => $frame
        ]);
    }
    public function update(Request $request, $id) {
        $this->validate($request,[
            'title' => 'required',
            'image' => 'nullable|image'
        ]);
        $frame = Framework::find($id);
        $frame->update($request->all());
        $frame->uploadImage($request->file('image'));
        return redirect()->route('frames.index')->with('message','Инструмент успешно обновлен');
    }

    public function destroy($id){
        Framework::find($id)->remove();
        return redirect()->route('frames.index')->with('message','Инструмент успешно удален');
    }
}

app/Http/Controllers/Backend/PostsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Category;
use App\Post;
use App\Tag;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

class PostsController extends Controller
{
    public function index() {
        $posts = Post::orderBy('created_at','desc')->paginate(7);
        return view('backend.posts.index', ['posts' => $posts]);
    }
    public function create(){
        $tags = Tag::pluck('title','id')->all();
        $categories = Category::pluck('title','id')->all();
        return view('backend.posts.create',[
            'tags' => $tags,
            'categories' => $categories
        ]);
    }
    public function store(Request $request){
        $this->validate($request,[
            'title' => 'required',
            'content' => 'required',
            'image' => 'nullable|image'
        ]);
        $post = Post::add($request->all());
        $post->uploadImage($request->file('image'));
        $post->setCategory($request->get('category_id'));
        $post->setTags($request->get('tags'));
        $post->toggleStatus($request->get('status'));
        $post->toggleFeatured($request->get('is_featured'));
        return redirect()->route('posts.index')->with('message','Статья успешно добавлена');
    }
    public function edit($id){
        $post = Post::find($id);
        $tags = Tag::pluck('title','id')->all();
        $categories = Category::pluck('title','id')->all();
        $selectedTags = $post->tags->pluck('id')->all();
        return view('backend.posts.edit',[
            'post' => $post,
            'tags' => $tags,
            'categories' => $categories,
            'selectedTags' => $selectedTags
        ]);
    }
    public function update(Request $request, $id){
        $this->validate($request,[
            'title' => 'required',
            'content' => 'required',
            'date' => 'required',
            'image' => 'nullable|image'
        ]);
        $post = Post::find($id);
        $post->edit($request->all());
        $post->uploadImage($request->file('image'));
        $post->setCategory($request->get('category_id'));
        $post->setTags($request->get('tags'));
        $post->toggleStatus($request->get('status'));
        $post->toggleFeatured($request->get('is_featured'));
        return redirect()->route('posts.index')->with('message','Статья успешно обновлена');
    }
    public function destroy($id){
        Post::find($id)->remove();
        return redirect()->route('posts.index')->with('message','Статья успешно удалена');
    }

}

app/Http/Controllers/Backend/SubsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Subscription;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SubsController extends Controller
{
    public function index() {
        $subs = Subscription::all();
        return view('backend.subs.index',['subs' => $subs]);
    }
    public function create(){
        return view('backend.subs.create');
    }
    public function store(Request $request) {
        $this->validate($request, [
            'email' => 'required|email|unique:subscriptions'
        ]);
        Subscription::add($request->get('email'));
        return redirect()->route('subscribers.index');
    }
    public function destroy($id){
        Subscription::find($id)->delete();
        return redirect()->route('subscribers.index');
    }
}

resources/views/backend/works_up/index.blade.php
@extends('backend.layout')

@section('content')
    <div class="page has-sidebar-left">
        <header class="blue accent-3 relative">
            <div class="container-fluid text-white">
                <div class="row p-t-b-10 ">
                    <div class="col">
                        <h4>
                            <i class="icon-package"></i>
                            Проекты
                        </h4>
                    </div>
                </div>
                <div class="row">
                    <ul class="nav responsive-tab nav-material nav-material-white">
                        <li>
                            <a class="nav-link active" href="{{route('works_up.index')}}"><i class="icon icon-list"></i>Все</a>
                        </li>
                        <li>
                            <a class="nav-link" href="{{route('works_up.create')}}"><i
                                        class="icon icon-plus-circle"></i> Добавить проект</a>
                        </li>
                    </ul>
                </div>
            </div>
        </header>
        @include('backend.message.msg')
        <div class="container-fluid animatedParent animateOnce my-3">
            <div class="animated fadeInUpShort">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card no-b shadow">
                            <div class="card-body p-0">
                                <div class="table-responsive">
                                    @if($works)
                                    <table class="table table-hover ">
                                        <tbody>
                                        @foreach($works as $work)
                                        <tr class="no-b">
                                            <td class="w-10">
                                                <img src="{{$work->getImage()}}" alt="">
                                            </td>
                                            <td class="w-10">
                                                <img src="{{$work->getImageTwo()}}" alt="">
                                            </td>
                                            <td class="w-10">
                                                <img src="{{$work->getImageThree()}}" alt="">
                                            </td>
                                            <td class="w-10">
                                                <img src="{{$work->getImageBlocks()}}" alt="">
                                            </td>
                                            <td>
                                                <h6>{{$work->title}}</h6>
                                                <small class="text-muted"></small>
                                            </td>
                                            @if($work->is_slider == 1)
                                            <td><span class="badge badge-success">Вид слайда</span></td>
                                            @else
                                                <td><span class="badge badge-danger">Обычный вид</span></td>
                                            @endif
                                            <td>
                                                <span><i class="icon icon-timer"></i> {{$work->created_at}}</span>
                                            </td>
                                            <td>
                                                <a href="{{route('works_up.edit', $work->id)}}" class="btn-fab btn-fab-sm btn-primary shadow text-white"><i class="icon-pencil"></i></a>
                                                {{Form::open(['route'=>['works_up.destroy', $work->id], 'method'=>'delete'])}}
                                                <button type="submit" class="btn btn-danger btn-xs"><i class="icon-remove"></i></button>
                                                {{Form::close()}}
                                            </td>
                                        </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <nav class="pt-3" aria-label="Page navigation">
                    {{$works->links()}}
                </nav>
            </div>
        </div>
    </div>
@endsection